// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
	"database/sql"
)

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (user_id, name, color_hex) VALUES (?, ?, ?)
`

type CreateProjectParams struct {
	UserID   int32
	Name     string
	ColorHex sql.NullString
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject, arg.UserID, arg.Name, arg.ColorHex)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProjectById = `-- name: GetProjectById :one
SELECT id, user_id, name, color_hex, created_at FROM projects WHERE id = ?
`

func (q *Queries) GetProjectById(ctx context.Context, id int32) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectById, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ColorHex,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectsByUserId = `-- name: GetProjectsByUserId :many
SELECT projects.id, projects.user_id, projects.name, projects.color_hex, projects.created_at 
FROM projects 
LEFT JOIN shared_projects sp ON projects.id = sp.project_id
WHERE projects.user_id = ? OR sp.shared_with_user_id = ?
ORDER BY created_at DESC
`

type GetProjectsByUserIdParams struct {
	UserID int32
}

func (q *Queries) GetProjectsByUserId(ctx context.Context, arg GetProjectsByUserIdParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getProjectsByUserId, arg.UserID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ColorHex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isProjectSharedWithUser = `-- name: IsProjectSharedWithUser :one
SELECT EXISTS(SELECT 1 FROM shared_projects WHERE project_id = ? AND shared_with_user_id = ?) AS is_shared
`

type IsProjectSharedWithUserParams struct {
	ProjectID        int32
	SharedWithUserID int32
}

func (q *Queries) IsProjectSharedWithUser(ctx context.Context, arg IsProjectSharedWithUserParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isProjectSharedWithUser, arg.ProjectID, arg.SharedWithUserID)
	var is_shared bool
	err := row.Scan(&is_shared)
	return is_shared, err
}

const shareProjectWithUser = `-- name: ShareProjectWithUser :exec
INSERT INTO shared_projects (project_id, shared_with_user_id) VALUES (?, ?)
`

type ShareProjectWithUserParams struct {
	ProjectID        int32
	SharedWithUserID int32
}

func (q *Queries) ShareProjectWithUser(ctx context.Context, arg ShareProjectWithUserParams) error {
	_, err := q.db.ExecContext(ctx, shareProjectWithUser, arg.ProjectID, arg.SharedWithUserID)
	return err
}

const unshareProjectWithUser = `-- name: UnshareProjectWithUser :exec
DELETE FROM shared_projects WHERE project_id = ? AND shared_with_user_id = ?
`

type UnshareProjectWithUserParams struct {
	ProjectID        int32
	SharedWithUserID int32
}

func (q *Queries) UnshareProjectWithUser(ctx context.Context, arg UnshareProjectWithUserParams) error {
	_, err := q.db.ExecContext(ctx, unshareProjectWithUser, arg.ProjectID, arg.SharedWithUserID)
	return err
}

const updateProject = `-- name: UpdateProject :exec
UPDATE projects SET name = ?, color_hex = ? WHERE id = ?
`

type UpdateProjectParams struct {
	Name     string
	ColorHex sql.NullString
	ID       int32
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.ExecContext(ctx, updateProject, arg.Name, arg.ColorHex, arg.ID)
	return err
}
