// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	// Crea un nuovo utente e restituisce l'utente appena creato.
	CreateUser(ctx context.Context, arg CreateUserParams) error
	// Elimina un utente e restituisce l'utente eliminato.
	DeleteUser(ctx context.Context, id int32) error
	// Recupera un utente dal suo indirizzo email.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Recupera un utente dal suo indirizzo email e dalla password.
	GetUserByEmailAndPassword(ctx context.Context, arg GetUserByEmailAndPasswordParams) (User, error)
	// Recupera un utente dal suo ID.
	GetUserByID(ctx context.Context, id int32) (User, error)
	// Recupera gli utenti che corrispondono a un termine di ricerca.
	GetUserByTerm(ctx context.Context, dollar_1 interface{}) ([]User, error)
	// Aggiorna un utente esistente e restituisce l'utente aggiornato.
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
