// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const completeTask = `-- name: CompleteTask :exec
INSERT INTO task_logs (task_id, completed_by_user_id) VALUES (?, ?)
`

type CompleteTaskParams struct {
	TaskID            int32
	CompletedByUserID int32
}

func (q *Queries) CompleteTask(ctx context.Context, arg CompleteTaskParams) error {
	_, err := q.db.ExecContext(ctx, completeTask, arg.TaskID, arg.CompletedByUserID)
	return err
}

const createTask = `-- name: CreateTask :execresult
INSERT INTO tasks (project_id, title, description, task_type, priority, created_by_user_id) 
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	ProjectID       sql.NullInt32
	Title           string
	Description     sql.NullString
	TaskType        TasksTaskType
	Priority        sql.NullInt32
	CreatedByUserID int32
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTask,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.TaskType,
		arg.Priority,
		arg.CreatedByUserID,
	)
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getCompletionsForWeek = `-- name: GetCompletionsForWeek :many
SELECT id, task_id, completed_by_user_id, completed_at
FROM task_logs
WHERE completed_by_user_id = ?
  AND completed_at >= ?
  AND completed_at < ?
ORDER BY completed_at DESC
`

type GetCompletionsForWeekParams struct {
	UserID    int32
	StartDate sql.NullTime
	EndDate   sql.NullTime
}

func (q *Queries) GetCompletionsForWeek(ctx context.Context, arg GetCompletionsForWeekParams) ([]TaskLog, error) {
	rows, err := q.db.QueryContext(ctx, getCompletionsForWeek, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskLog
	for rows.Next() {
		var i TaskLog
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.CompletedByUserID,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScheduledTasksForDateRange = `-- name: GetScheduledTasksForDateRange :many
SELECT td.id, td.task_id, td.date
FROM task_dates td
WHERE td.task_id IN (
    SELECT t.id FROM tasks t
    LEFT JOIN shared_tasks st ON t.id = st.task_id
    WHERE t.created_by_user_id = ? OR st.shared_with_user_id = ?
)
AND td.date >= ? AND td.date <= ?
ORDER BY td.date ASC
`

type GetScheduledTasksForDateRangeParams struct {
	UserID    int32
	StartDate time.Time
	EndDate   time.Time
}

func (q *Queries) GetScheduledTasksForDateRange(ctx context.Context, arg GetScheduledTasksForDateRangeParams) ([]TaskDate, error) {
	rows, err := q.db.QueryContext(ctx, getScheduledTasksForDateRange,
		arg.UserID,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskDate
	for rows.Next() {
		var i TaskDate
		if err := rows.Scan(&i.ID, &i.TaskID, &i.Date); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskById = `-- name: GetTaskById :one
SELECT id, project_id, title, description, task_type, priority, created_by_user_id, created_at
FROM tasks WHERE id = ?
`

func (q *Queries) GetTaskById(ctx context.Context, id int32) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskById, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.TaskType,
		&i.Priority,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskCompletions = `-- name: GetTaskCompletions :many
SELECT id, task_id, completed_by_user_id, completed_at
FROM task_logs WHERE task_id = ? ORDER BY completed_at DESC
`

func (q *Queries) GetTaskCompletions(ctx context.Context, taskID int32) ([]TaskLog, error) {
	rows, err := q.db.QueryContext(ctx, getTaskCompletions, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskLog
	for rows.Next() {
		var i TaskLog
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.CompletedByUserID,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskDates = `-- name: GetTaskDates :many
SELECT id, task_id, date FROM task_dates WHERE task_id = ? ORDER BY date ASC
`

func (q *Queries) GetTaskDates(ctx context.Context, taskID int32) ([]TaskDate, error) {
	rows, err := q.db.QueryContext(ctx, getTaskDates, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskDate
	for rows.Next() {
		var i TaskDate
		if err := rows.Scan(&i.ID, &i.TaskID, &i.Date); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskListByProjectId = `-- name: GetTaskListByProjectId :many
SELECT id, project_id, title, description, task_type, priority, created_by_user_id, created_at 
FROM tasks 
WHERE project_id = ? 
ORDER BY created_at DESC
`

func (q *Queries) GetTaskListByProjectId(ctx context.Context, projectID sql.NullInt32) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTaskListByProjectId, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.TaskType,
			&i.Priority,
			&i.CreatedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByUserId = `-- name: GetTasksByUserId :many
SELECT tasks.id, tasks.project_id, tasks.title, tasks.description, tasks.task_type, tasks.priority, tasks.created_by_user_id, tasks.created_at
FROM tasks
LEFT JOIN shared_tasks ON tasks.id = shared_tasks.task_id
WHERE tasks.created_by_user_id = ? OR shared_tasks.shared_with_user_id = ?
ORDER BY tasks.created_at DESC
`

type GetTasksByUserIdParams struct {
	UserID int32
}

func (q *Queries) GetTasksByUserId(ctx context.Context, arg GetTasksByUserIdParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByUserId, arg.UserID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.TaskType,
			&i.Priority,
			&i.CreatedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnscheduledTasksByUserId = `-- name: GetUnscheduledTasksByUserId :many
SELECT t.id, t.project_id, t.title, t.description, t.task_type, t.priority, t.created_by_user_id, t.created_at
FROM tasks t
LEFT JOIN shared_tasks st ON t.id = st.task_id
WHERE (t.created_by_user_id = ? OR st.shared_with_user_id = ?)
  AND t.id NOT IN (SELECT td.task_id FROM task_dates td)
ORDER BY t.created_at DESC
`

type GetUnscheduledTasksByUserIdParams struct {
	UserID int32
}

func (q *Queries) GetUnscheduledTasksByUserId(ctx context.Context, arg GetUnscheduledTasksByUserIdParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getUnscheduledTasksByUserId, arg.UserID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.TaskType,
			&i.Priority,
			&i.CreatedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isTaskSharedWithUser = `-- name: IsTaskSharedWithUser :one
SELECT EXISTS(SELECT 1 FROM shared_tasks WHERE task_id = ? AND shared_with_user_id = ?) AS is_shared
`

type IsTaskSharedWithUserParams struct {
	TaskID           int32
	SharedWithUserID int32
}

func (q *Queries) IsTaskSharedWithUser(ctx context.Context, arg IsTaskSharedWithUserParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isTaskSharedWithUser, arg.TaskID, arg.SharedWithUserID)
	var is_shared bool
	err := row.Scan(&is_shared)
	return is_shared, err
}

const scheduleTask = `-- name: ScheduleTask :exec
INSERT INTO task_dates (task_id, date) VALUES (?, ?)
`

type ScheduleTaskParams struct {
	TaskID int32
	Date   time.Time
}

func (q *Queries) ScheduleTask(ctx context.Context, arg ScheduleTaskParams) error {
	_, err := q.db.ExecContext(ctx, scheduleTask, arg.TaskID, arg.Date)
	return err
}

const shareTaskWithUser = `-- name: ShareTaskWithUser :exec
INSERT INTO shared_tasks (task_id, shared_with_user_id) VALUES (?, ?)
`

type ShareTaskWithUserParams struct {
	TaskID           int32
	SharedWithUserID int32
}

func (q *Queries) ShareTaskWithUser(ctx context.Context, arg ShareTaskWithUserParams) error {
	_, err := q.db.ExecContext(ctx, shareTaskWithUser, arg.TaskID, arg.SharedWithUserID)
	return err
}

const uncompleteTask = `-- name: UncompleteTask :exec
DELETE FROM task_logs
WHERE task_id = ? AND completed_by_user_id = ? AND DATE(completed_at) = CURDATE()
`

type UncompleteTaskParams struct {
	TaskID            int32
	CompletedByUserID int32
}

func (q *Queries) UncompleteTask(ctx context.Context, arg UncompleteTaskParams) error {
	_, err := q.db.ExecContext(ctx, uncompleteTask, arg.TaskID, arg.CompletedByUserID)
	return err
}

const unscheduleTask = `-- name: UnscheduleTask :exec
DELETE FROM task_dates WHERE task_id = ? AND date = ?
`

type UnscheduleTaskParams struct {
	TaskID int32
	Date   time.Time
}

func (q *Queries) UnscheduleTask(ctx context.Context, arg UnscheduleTaskParams) error {
	_, err := q.db.ExecContext(ctx, unscheduleTask, arg.TaskID, arg.Date)
	return err
}

const unshareTaskWithUser = `-- name: UnshareTaskWithUser :exec
DELETE FROM shared_tasks WHERE task_id = ? AND shared_with_user_id = ?
`

type UnshareTaskWithUserParams struct {
	TaskID           int32
	SharedWithUserID int32
}

func (q *Queries) UnshareTaskWithUser(ctx context.Context, arg UnshareTaskWithUserParams) error {
	_, err := q.db.ExecContext(ctx, unshareTaskWithUser, arg.TaskID, arg.SharedWithUserID)
	return err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks
SET project_id = ?, title = ?, description = ?, task_type = ?, priority = ?
WHERE id = ?
`

type UpdateTaskParams struct {
	ProjectID   sql.NullInt32
	Title       string
	Description sql.NullString
	TaskType    TasksTaskType
	Priority    sql.NullInt32
	ID          int32
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateTask,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.TaskType,
		arg.Priority,
		arg.ID,
	)
	return err
}

const updateTaskProject = `-- name: UpdateTaskProject :exec
UPDATE tasks SET project_id = ? WHERE id = ?
`

type UpdateTaskProjectParams struct {
	ProjectID sql.NullInt32
	ID        int32
}

func (q *Queries) UpdateTaskProject(ctx context.Context, arg UpdateTaskProjectParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskProject, arg.ProjectID, arg.ID)
	return err
}
